name: flutter_fancy_tree_view
description: >
  A collection of widgets and slivers that helps bringing hierarchical data to life.
version: 1.2.0
homepage: https://baumths.github.io/flutter_tree_view
repository: https://github.com/baumths/flutter_tree_view

environment:
  sdk: ^3.1.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

screenshots:
  - description: A TreeView with lines connecting tree nodes.
    path: screenshots/connecting_lines.png
  - description: A TreeView with lines scoping the levels of tree nodes.
    path: screenshots/scoping_lines.png
  - description: A TreeView with blank indentations.
    path: screenshots/blank_indentation.png

topics:
  - layout
  - ui
